/* global Pixie */

return function(tag_name, name_space) {
  if (name_space) {
    return new Pixie([document.createElementNS(name_space, tag_name)]);
  }
  let tag;
  switch (tag_name.toLowerCase()) {
    case '!doctype':
    case 'a':
    case 'abbr':
    case 'address':
    case 'area':
    case 'article':
    case 'aside':
    case 'audio':
    case 'b':
    case 'base':
    case 'bdi':
    case 'bdo':
    case 'blockquote':
    case 'body':
    case 'br':
    case 'button':
    case 'canvas':
    case 'caption':
    case 'cite':
    case 'code':
    case 'col':
    case 'colgroup':
    case 'datalist':
    case 'dd':
    case 'del':
    case 'details':
    case 'dfn':
    case 'dialog':
    case 'div':
    case 'dl':
    case 'dt':
    case 'em':
    case 'embed':
    case 'dieldset':
    case 'figcaption':
    case 'figure':
    case 'footer':
    case 'form':
    case 'h1':
    case 'h2':
    case 'h3':
    case 'h4':
    case 'h5':
    case 'h6':
    case 'head':
    case 'header':
    case 'hr':
    case 'html':
    case 'i':
    case 'iframe':
    case 'img':
    case 'input':
    case 'ins':
    case 'kbd':
    case 'keygen':
    case 'label':
    case 'legend':
    case 'li':
    case 'link':
    case 'main':
    case 'map':
    case 'mark':
    case 'menu':
    case 'menuitem':
    case 'meta':
    case 'meter':
    case 'nav':
    case 'noscript':
    case 'object':
    case 'ol':
    case 'optgroup':
    case 'option':
    case 'output':
    case 'p':
    case 'param':
    case 'pre':
    case 'progress':
    case 'q':
    case 'rp':
    case 'rt':
    case 'ruby':
    case 's':
    case 'samp':
    case 'script':
    case 'section':
    case 'select':
    case 'small':
    case 'source':
    case 'span':
    case 'strong':
    case 'style':
    case 'sub':
    case 'summary':
    case 'sup':
    case 'table':
    case 'tbody':
    case 'td':
    case 'textarea':
    case 'tfoot':
    case 'th':
    case 'thead':
    case 'time':
    case 'title':
    case 'tr':
    case 'track':
    case 'u':
    case 'ul':
    case 'var':
    case 'video':
    case 'wbr':
      tag = document.createElementNS('http://www.w3.org/1999/xhtml', tag_name);
      break;
    case 'altglyph':
    case 'altglyphdef':
    case 'altglyphitem':
    case 'animate':
    case 'animatecolor':
    case 'animatemotion':
    case 'animatetransform':
    case 'circle':
    case 'clippath':
    case 'color-profile':
    case 'cursor':
    case 'defs':
    case 'desc':
    case 'ellipse':
    case 'feblend':
    case 'fecolormatrix':
    case 'fecomponenttransfer':
    case 'fecomposite':
    case 'feconvolvematrix':
    case 'fediffuselighting':
    case 'fedisplacementmap':
    case 'fedistantlight':
    case 'feflood':
    case 'fefunca':
    case 'fefuncb':
    case 'fefuncg':
    case 'fefuncr':
    case 'fegaussianblur':
    case 'feimage':
    case 'femerge':
    case 'femergenode':
    case 'femorphology':
    case 'feoffset':
    case 'fepointlight':
    case 'fespecularlighting':
    case 'fespotlight':
    case 'fetile':
    case 'feturbulence':
    case 'filter':
    case 'font':
    case 'font-face':
    case 'font-face-format':
    case 'font-face-name':
    case 'font-face-src':
    case 'font-face-uri':
    case 'foreignobject':
    case 'g':
    case 'glyph':
    case 'glyphref':
    case 'hkern':
    case 'image':
    case 'line':
    case 'linergradient':
    case 'marker':
    case 'mask':
    case 'metadata':
    case 'missing-glyph':
    case 'mpath':
    case 'path':
    case 'pattern':
    case 'polygon':
    case 'polyline':
    case 'radialgradient':
    case 'rect':
    case 'set':
    case 'stop':
    case 'svg':
    case 'switch':
    case 'symbol':
    case 'text':
    case 'textpath':
    case 'tref':
    case 'tspan':
    case 'use':
    case 'view':
    case 'vkern':
      tag = document.createElementNS('http://www.w3.org/2000/svg', tag_name);
      break;
    default:
      tag = document.createElement(tag_name);
      break;
  }
  return new Pixie([tag]);
};
